name: actionPractice

on:
  push:
    branches:
      - main
      - release/*
 # workflow_dispatch:
env:
  FIRST_NAME: ${{ vars.FIRST_NAME }}
jobs:
  first_job:
     env:
       LAST_NAME: ${{ secrets.LAST_NAME }}
     name: Hello Job
     runs-on: ubuntu-24.04
     steps:
       - name: Checkout
         uses: actions/checkout@v6.0.3
          
       - name: Greetings
         env:
           WELL: Kemcho
         run: echo "Hello $FIRST_NAME $LAST_NAME $WELL?"
       - name: List files
         run: ls -a

