name: terraform_pipeline
on: 
  push:
    branches:
      - main
  pull_request: 
      branches:
        - develop
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform_job:
     name: Terraform job
     runs-on: ubuntu-22.04

     steps:
       - name: HashiCorp - Setup Terraform
         uses: hashicorp/setup-terraform@v2.0.3
         
       - name: Checkout
         uses: actions/checkout@v6.0.3 
         
       - name: terraform init
         run: terraform init

       - name: terraform validate
         run: terraform validate

       - name: terraform plan
         run: terraform plan
    

      
