name: practice_pipeline
on: 
  push:
    branches:
      - main
  pull_request: 
      branches:
        - develop
jobs:
  terraform_job:
     name: Terraform job
     runs-on: ubuntu-22.04

     steps:
       - name: terraform init
         run: terraform init

       - name: terraform validate
         run: terraform validate

       - name: terraform plan
         run: terraform plan
    

      
